# Generated by Django 4.2 on 2025-10-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('nivel', models.IntegerField(default=1)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='Name',
            new_name='name',
        ),
    ]
