# Generated by Django 4.2 on 2025-10-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_entrenador_rename_name_pokemon_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenador',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='Height',
            new_name='altura',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='weigth',
            new_name='peso',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='type',
            new_name='tipo',
        ),
    ]
