# Generated by Django 4.2 on 2025-10-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_rename_nombre_entrenador_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenador',
            old_name='name',
            new_name='nombre',
        ),
    ]
