# Generated by Django 4.2 on 2025-10-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_rename_name_entrenador_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='imagen',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
