# Generated by Django 4.2 on 2025-10-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_pokemon_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.entrenador'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
